### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by zevv** [NotKit/kernel-3.18-alps-x600#1]
Hi, are there any tricks to building this kernel? I run into various issues with missing include paths to mt6797 specific directories.

Trying to build with aarch64-linux-android-gcc 4.9 from ndk 16b.

Thanks,

**Comment by NotKit** [comment]
Hi,
You need to build out-of-tree with O= option. I've added build instructions to Gemian wiki: https://github.com/gemian/gemini-keyboard-apps/wiki/KernelCompilation

**Comment by zevv** [comment]
Thanks for that, building succeeded.

**Comment by zevv** [comment]
Hi,

Are you the owner/administrator of the Github geminan linux-kernel-3.18
repo?  Could you please enable the github issues for this repository,
there's some things I'd like to discuss regarding kernel work and
Android/Linux compatibility.

Thanks,

Ico

--
:wq
^X^Cy^K^X^C^C^C^C
